### ISSUE TITLE
doubts in do_evaluation and analytical_solution function

### ISSUE THREAD

**Issue by ashishagg70** [awasthiabhijeet/cs725-2020-assign1#1]
do_evaluation should use regularized loss function when evaluation loss for analytical solution rather it is using  mse_loss.
I think C should be passed to do_evaluation and inside loss_fn should be called rather than mse_loss. 

am I missing something ? please clarify.

**Comment by awasthiabhijeet** [comment]
Since the evaluation metric is mean square error, the evaluation function does not consider the regularization component.
In general, the loss function you are trying to minimize is kind of your choice (in this assignment, you only get to choose the value of C). But the evaluation metric is usually pre-specified and need not be the same as the loss function.

**Comment by ashishagg70** [comment]
Got it. Thanks
